### PR TITLE
Fix anchor link in usage readme

### PR DESCRIPTION
**Pull request by marktefftech**

### CODE REVIEW

**Comment by marktefftech** [comment]
While we're here, can someone (maybe @DonggeLiu) please clarify something for me:

Does a project need to already be integrated with FuzzBench in order to get results from this LLM-approach?
I read both blog posts and this is not clear... thank you

**Comment by marktefftech** [comment]
FWIW test failures seems to be auth-related, feel free to close this PR if you want, but the anchor link is not working

**Comment by DonggeLiu** [comment]
Thanks for noticing and fixing the link, @marktefftech!

> Does a project need to already be integrated with FuzzBench in order to get results from this LLM-approach? I read both blog posts and this is not clear... thank you

Yep, but it is [OSS-Fuzz](https://github.com/google/oss-fuzz), not FuzzBench : )
In order to build LLM-generated fuzz targets and get their coverage evaluation results, this platform needs to utilize the [Dockerfile, build script, and fuzz target](https://github.com/google/oss-fuzz/tree/master/projects/example) of an existing fuzz target of the project.
However, if evaluation is not required, people should still be able to use this framework to generate fuzz targets for projects not yet in OSS-Fuzz.

A side note: FuzzBench also makes use of OSS-Fuzz project. FuzzBench uses OSS-Fuzz fuzz targets as benchmarks to evaluate fuzzers.

**Comment by DonggeLiu** [comment]
> FWIW test failures seems to be auth-related, feel free to close this PR if you want, but the anchor link is not working

Yep this is unrelated, I will merge your PR.

**Review by DonggeLiu — APPROVED** [review]

**Pull request merged**
