### PR TITLE
[JVM] Add retry logic for JVM

### PR DESCRIPTION
**Pull request by arthurscchan**
This PR add back the retry logic for JVM when the first generated harness is failed to build.

### CODE REVIEW

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-740-1 -m vertex_ai_gemini-1-5 -i -b test-to-harness-jvm-small

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-740-1 -m vertex_ai_gemini-1-5 -i -b jvm-small

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-740-2 -m vertex_ai_gemini-1-5 -i -b test-to-harness-jvm-small

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-740-3 -m vertex_ai_gemini-1-5 -i -b comparison

**Comment by DavidKorczynski** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-12-04-740-ascc-jvm-pr-740-3-comparison/index.html

**Review by DavidKorczynski — CHANGES_REQUESTED** [review]
.

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-740-4 -m vertex_ai_gemini-1-5 -i -b test-to-harness-jvm-small

**Comment by DavidKorczynski** [comment]
There's a result now: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-12-04-740-ascc-jvm-pr-740-4-test-to-harness-jvm-small/index.html

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-740-5 -m vertex_ai_gemini-1-5 -i -b jvm-small

**Comment by DavidKorczynski** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-12-04-740-ascc-jvm-pr-740-5-jvm-small/index.html

**Comment by DavidKorczynski** [comment]
both java experiments are looking good

**Comment by DavidKorczynski** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-12-04-740-dgk123-comparison/index.html

**Review by DavidKorczynski — APPROVED** [review]
Java builds are looking real nice.

**Pull request merged**
