### PR TITLE
Display triage prompt on web

### PR DESCRIPTION
**Pull request by fdt622**
This PR displays the triage prompt on the web, making it easier to read and evaluate the factors affecting LLM triage.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Thanks @fdt622, this looks great to me.
Could you please fix the minor linter error?

Meanwhile, let me create a branch and rebased your PR on it so that we can run a test exp before merging.

**Review by DonggeLiu — APPROVED** [review]

**Comment by fdt622** [comment]
> Thanks @fdt622, this looks great to me. Could you please fix the minor linter error?
> 
> Meanwhile, let me create a branch and rebased your PR on it so that once you fix the linter error, we can merge your PR into the new branch and run a test exp before merging into main.

Hi @DonggeLiu, I have fixed the linter error.

**Comment by DonggeLiu** [comment]
Thanks!
BTW, do you happen to have [this](https://github.com/google/oss-fuzz-gen/blob/main/USAGE.md#auto-format--lint) installed? It can check lint/format issues locally, without having to wait for CIs after pushing a commit.

**Comment by fdt622** [comment]
> Thanks! BTW, do you happen to have [this](https://github.com/google/oss-fuzz-gen/blob/main/USAGE.md#auto-format--lint) installed? It can check lint/format issues locally, without having to wait for CIs after pushing a commit.

Thanks, I would use it to check locally.

**Comment by DonggeLiu** [comment]
Running experiments on https://github.com/google/oss-fuzz-gen/pull/546

**Pull request merged**
