### PR TITLE
builder_runner: store summary.json in workdir in cloud runs

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This will make post processing of results easier, also when downloading the reports locally.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-10 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-11 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-12 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-15 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-16 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
https://github.com/google/oss-fuzz/pull/12522 fixed the experiments

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-17 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-18 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-19 -b minor-for-ci -ns 2

**Comment by DavidKorczynski** [comment]
Experiment is good: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-21-636-d-cov-19-minor-for-ci/index.html

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
