### PR TITLE
re-select comparison benchmark set

### LINKED ISSUE #90: Re-select `comparison` becnhmark-set from the new benchmarks.
This requires looking into the failures and selecting benchmarks from [recent results](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-11-64-dg-comparison/sort.html) based on the following guidelines:
1. < 30 benchmarks in total. This ensures we can finish the experiment quickly. Particularly for PR experiments.
2. <=2 benchmarks from one project to include more projects.
3. <= 1 benchmark with a 100% build rate or > 10% coverage increase from one project, with ~10 benchmarks in total. Well-performing benchmarks are for regression checks; No point in having too many.
4. <=1 benchmark failed with the same error from the same project to track improvements.
5. Avoid the same general error from different projects (e.g., `size_t` or others from standard lib undefined)
6. Interesting projects to include:
  * `tinyxml2`
  * `icu`
  * `avahi`
  * Project with complex function signature (e.g., #89, `abseil-cpp`, `cppitertools`'s `operator*`, etc.)
7. Some interesting failures to include in `comparison`:
  * Incorrect path in `#include <...>` / Undefined function.
  * Missing build failure.
  * Function not called.
  * Incorrect function usage.
  * Need the defs of data types used in the function under test.
  * Incorrect usage of the function under test.
8. <=1 relatively good performing benchmark from a project (e.g., 60% build rate, 1% coverage increase).

Given there are many benchmarks to select, please document all selected benchmarks with justification [here](https://docs.google.com/spreadsheets/d/1XR6k942PioBFICmPB9a31X3BG1UqY1_lXIrmc5pq9LQ/edit#gid=0) for future references.
Feel free to document some interesting benchmarks that are not selected or not sure if they should be selected.

### PR DESCRIPTION
**Pull request by cjx10**
Resolves #90 
Open for suggestions :)

### CODE REVIEW

**Comment by cjx10** [comment]
Will update this set after pr #97

**Comment by DonggeLiu** [comment]
Thanks, @cjx10.

Leaving the link to the justifications you wrote:
https://docs.google.com/spreadsheets/d/1XR6k942PioBFICmPB9a31X3BG1UqY1_lXIrmc5pq9LQ/edit#gid=0

**Comment by DonggeLiu** [comment]
@oliverchang This is the new comparison benchmark set.
The conflicts are because of frequently updated benchmarks in the past few days, and should be relatively easy to solve even by a manual ctrl-f.

**Review by oliverchang — APPROVED** [review]
LGTM. Maybe also include cjson and libplist as two projects that we found real bugs in. 

Also libvpx looks interesting, as a case that has never succeeded any build before. 

And also openssl, as a critical project that would benefit from improvements.

**Comment by DonggeLiu** [comment]
Thanks! They look great!
2 minor questions:
1. `cmake` has some failures due to incorrect lib (path), e.g., ([`cmake-externalentityinitprocessor/01`](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-02-19-weekly-all/sample/output-cmake-externalentityinitprocessor/01), [`output-cmake-xml_externalentityparsercreate/09`](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-02-19-weekly-all/sample/output-cmake-xml_externalentityparsercreate/09)). `cmake-xml_externalentityparsercreate` had 1 successful target in the experiment. Would they be interesting to consider given we will add path info after using FI APIs?
2. `tinyxml2-tinyxml2::xmlelement::shallowclone` was a pretty interesting case we used in the blog post, may I ask why it is not preferred?
Thanks!

**Review by DonggeLiu — APPROVED** [review]
Thanks! The spreadsheet documentation is very helpful : )

**Comment by cjx10** [comment]
> Just to triple-check: No benchmark function is the caller/callee of another one right?

Don't think there's any based on what functions are suggested by FI, but will do a quick check on the source code

**Comment by cjx10** [comment]
> 2 minor questions:

`cmake` is not included because of its extra long building time
`shallowclone` from `tinyxml2` is indeed interesting, it has some unique errors in calling class members that I haven't found in other projects. Shall replace `setattribute` with this instead.

**Comment by cjx10** [comment]
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1/llm-experiment/default/ofg-pr-99-jc
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-99-jc-comparison/index.html

**Comment by DonggeLiu** [comment]
The report looks good!
Please feel free to merge this if you like : )

Some potential erroneous function signatures:
1. Strip `std::  1`:
    1. [`cppitertools-void Iterator(std::__1::allocator<char> > &> *, std::__1::allocator<char> >, size_t)`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-99-jc-comparison/benchmark/output-cppitertools-_zn4iter4impl10combinatorirnst3__112basic_stringicns2_11char_traitsiceens2_9allocatoriceeeee8iterato)
    2. [`cppitertools-std::__1::allocator<bool> > &> std::__1::allocator<bool> > &>::operator++()`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-99-jc-comparison/benchmark/output-cppitertools-_zn4iter4impl10compressedirnst3__16vectoriins2_9allocatoriieeeerns3_ibns4_ibeeeee8iteratoris7_sa_epp)
    3. [`jsonnet-const AST * builtinExtVar(Interpreter *, const LocationRange, const std::__1::allocator<jsonnet::internal::(anonymous namespace)::Value> >)`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-99-jc-comparison/benchmark/output-jsonnet-_zn7jsonnet8internal12_global__n_111interpreter13builtinextvarerkns0_13locationrangeerknst3__16vectorins1)
2. Weird function name:
    1. [`eigen-void 1>::~Matrix()`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-99-jc-comparison/benchmark/output-eigen-_zn5eigen6matrixidlin1elin1eli0elin1elin1eed2ev)
    2. [`eigen-void true> >::resize(Index, Index)`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-99-jc-comparison/benchmark/output-eigen-_zn5eigen9transposeins_5blockins_6matrixinst3__17complexideelin1elin1eli0elin1elin1eeelin1eli1elb1eeee6resi)
    3. [`immer-result_t &>(2U> >, size_t, edit_t)`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-22-99-jc-comparison/benchmark/output-immer-_zn5immer6detail4rbts23slice_right_mut_visitorins1_4nodeiins_13memory_policyins_11heap_policyins_8cpp_heape)

I will document them in this spreadsheet.
If you happen to notice more, please consider adding them too.
Thanks!

**Pull request merged**
