### PR TITLE
LLM query improvements

### PR DESCRIPTION
**Pull request by DonggeLiu**
1. Set default temperature to 1.
2. Allow passing a list of temperatures to 1) explore more varieties and 2) avoid experiments being blocked by the 'recitation' error.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Report looks alright:
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-07-08-448-dg-comparison/index.html

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
