### PR TITLE
evaluator: fix build script lookup

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Following the change here https://github.com/google/oss-fuzz-gen/pull/623/files#diff-cc74274207721385b333564f0db8639bd5acf97ee8830228c2b7eccec65e23c1R238 when the existing call to `create_ossfuzz_project` https://github.com/google/oss-fuzz-gen/blob/a90775eab1d898ee9f4031a2f0b6263db023a437/experiment/evaluator.py#L359 calls the function, then a FileNotFoundError will be thrown here: https://github.com/google/oss-fuzz-gen/blob/a90775eab1d898ee9f4031a2f0b6263db023a437/experiment/evaluator.py#L264

This fixes it

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-152 -b minor-for-ci -ns 2 -rdn

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-153 -b minor-for-ci -ns 2 -rd

**Comment by DavidKorczynski** [comment]
Experiment looks good: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-10-02-659-d-cov-153-minor-for-ci/index.html

**Review by arthurscchan — APPROVED** [review]
Remark: if build_script_path not exist, this line could still throw an error.

**Pull request merged**
