### PR TITLE
run_one_experiment: ensure no parallel executions in local runs

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This causes issues with docker container reuse.

It's mentioned in the code: https://github.com/google/oss-fuzz-gen/blob/18e1af1569be850e588ee5b0319303bca583b622/run_one_experiment.py#L34-L39 

But I think a better workflow would be to adjust this automatically if there is no cloud run anyways.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Thanks @DavidKorczynski 

> This causes issues with docker container reuse.

Do you mean two trials may accidentally use the same docker containers (e.g., due to duplicate docker image/container names)?

> # WARN: Avoid NUM_EVA for local experiments. 

There is a typo in my comment here: I meant to say, `Avoid high value for NUM_EVA for local experiments.` This is because users may unintentionally use a lot more computation power.

**Comment by DavidKorczynski** [comment]
> Thanks @DavidKorczynski
> 
> > This causes issues with docker container reuse.
> 
> Do you mean two trials may accidentally use the same docker containers (e.g., due to duplicate docker image/container names)?
> 
> > `# WARN: Avoid NUM_EVA for local experiments. `
> 
> There is a typo in my comment here: I meant to say, `Avoid high value for NUM_EVA for local experiments.` This is because users may unintentionally use a lot more computation power.

The restarting of containers was in the end due to the issue fixed here: https://github.com/google/oss-fuzz-gen/pull/311 

Left this PR open because of the typo, as in either case I think we should do the following to make it easy to control this var: https://github.com/google/oss-fuzz-gen/pull/316

Let's close this and focus on the other two -- can submit a patch for the typo in case.

**Pull request closed without merging**
