### PR TITLE
Fix slow experiments

### PR DESCRIPTION
**Pull request by DonggeLiu**
This PR tries to investigate why [our recent experiments](https://pantheon.corp.google.com/kubernetes/cronjob/us-central1/llm-experiment/default/daily-comp/details?mods=logs_tg_prod&project=oss-fuzz) are running very slowly.
For example, the [daily exp on Mar 18](https://pantheon.corp.google.com/kubernetes/pod/us-central1/llm-experiment/default/daily-comp-28511520-fb2fx/details?mods=logs_tg_prod&project=oss-fuzz) took a few days.

This appears to start on Mar 18, because the previous daily exp (Mar 15) seems OK.
Based on the CPU usage, it may relate to our parallelization, but we surely did not change that during the weekend before 18th.

I will start by reverting all commits till [c8f2947e3b51ba8729c8101a6de8fa56f3ae2e12](https://github.com/google/oss-fuzz-gen/commit/c8f2947e3b51ba8729c8101a6de8fa56f3ae2e12), the first PR on Mar 15, 2024.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-177-dg
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-22-177-dg-comparison/index.html
BUCKET: https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-22-177-dg-comparison
BUCKET GS: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-22-177-dg-comparison`

**Comment by DonggeLiu** [comment]
Using the same code in this repo, this experiment still takes too long.
It took ~9.5 hours to complete (8:30 PM - 5 AM the next day), while it should finish within 3 hours.

Meanwhile, its CPU usage is never above 2, while it should be over 30. Here is a comparison:
This experiment:
image

The last 5 normal experiments:
image

**Comment by DonggeLiu** [comment]
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-177-dg
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-25-177-dg-comparison/index.html
BUCKET: https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-25-177-dg-comparison
BUCKET GS: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-25-177-dg-comparison`

**Comment by DonggeLiu** [comment]
Merged https://github.com/google/oss-fuzz/pull/11727

JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-177-dg-11727
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-25-177-dg-11727-comparison/index.html
BUCKET: https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-25-177-dg-11727-comparison
BUCKET GS: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-25-177-dg-11727-comparison`

**Comment by DonggeLiu** [comment]
Fixed some issues on OSS-Fuzz, will re-run the tests here.

**Comment by DonggeLiu** [comment]
JOB: https://console.cloud.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-177-dg-11727
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-27-177-dg-11727-comparison/index.html
BUCKET: https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-27-177-dg-11727-comparison
BUCKET GS: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-27-177-dg-11727-comparison`

**Comment by DonggeLiu** [comment]
@oliverchang Good news: I reckon your PR resolved the slowness issue. With a 5-minute fuzzing timeout, the new experiment terminated within 30 minutes, while the previous one took almost a day. 

I suppose [the `Running` instance](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-27-177-dg-11727-comparison/benchmark/output-libarchive-archive_entry_linkify) had `BrokenPipe` error. Although this does not affect experiment termination now, we may need to fix the code to capture this and re-run the experiment when this happens.

**Comment by oliverchang** [comment]
awesome! should we close this  PR then?

**Comment by DonggeLiu** [comment]
> awesome! should we close this PR then?

Yep

**Pull request closed without merging**
