### PR TITLE
testing: consumebytes/consumedata size issues

### PR DESCRIPTION
**Pull request by DavidKorczynski**
not to be merged

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n david-quick123 -b lpng -ns 4

**Comment by DavidKorczynski** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-17-620-david-quick123-lpng/index.html

**Comment by oliverchang** [comment]
/gcbrun exp -n david-quick123 -b lpng -ns 4

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n david-quick1234 -b lpng -ns 4

**Comment by DavidKorczynski** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-18-620-david-quick1234-lpng/index.html

**Pull request closed without merging**
