### PR TITLE
Push image for weekly experiments

### PR DESCRIPTION
**Pull request by DonggeLiu**
1. Add workflow to build a docker image with the latest code in `main`
2. Push the image to the artifact registry on Saturday at 1 AM.

I will also run some experiments here for testing purposes.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1/llm-experiment/default/ofg-pr-109-dg
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-02-16-109-dg-comparison/index.html

This is run on the new cluster.

**Comment by DonggeLiu** [comment]
Both reports look all right now.
Will test the new cluster at a large scale with `all` benchmarks.

**Comment by DonggeLiu** [comment]
No result from `icu` because of a failure in FI API:
https://introspector.oss-fuzz.com/api/function-signature?project=icu&function=_ZN6icu_7510UnicodeSet6retainERKNS_13UnicodeStringE


This will be addressed in #112

**Comment by DonggeLiu** [comment]
Testing a large scale experiment with `all` benchmark.
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1/llm-experiment-large/default/weekly-manual
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-02-19-weekly-comparison/index.html

**Comment by DonggeLiu** [comment]
Use Asian and European Vertex AI APIs.

**Comment by DonggeLiu** [comment]
Final test experiment before switching to cronjob:
MANUAL JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1/llm-experiment-large/default/weekly-manual-feb-23/details?project=oss-fuzz
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-02-23-weekly-all/index.html

**Review by mihaimaruseac — APPROVED** [review]

**Review by erfanio — APPROVED** [review]

**Pull request merged**
