### PR TITLE
CI: make it possible to redirect stdout/stderr from experiment

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Makes it possible to redirect stdout/stderr from experiment run using `-rd`

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-22 -b minor-for-ci -ns 1

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-23 -b minor-for-ci -ns 1

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-24 -b minor-for-ci -ns 1

**Comment by DavidKorczynski** [comment]
normal experiment looks good: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-22-639-d-cov-24-minor-for-ci/index.html

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n d-cov-25 -b minor-for-ci -ns 1 -rd

**Comment by DavidKorczynski** [comment]
Experiment with redirection looks good: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-22-639-d-cov-24-minor-for-ci/index.html

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
