### PR TITLE
report: make project summary table sortable

### PR DESCRIPTION
**Pull request by DavidKorczynski**
The new project summary table uses the sortable-table class but the current javascript logic only behaves well in the context of a single sortable-table. Since we now have two sortable-tables we need to adjust the javascript logic to handle this. The primary way of resolving this is making sure the sorting logic gets a hold of the right table as opposed to considering all `th` values as part of the same table.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-53121 -m vertex_ai_gemini-1-5 -b comparison

**Comment by DavidKorczynski** [comment]
Report from before the previous nit commit: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-16-537-dk-53121-comparison/index.html

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-5312121 -m vertex_ai_gemini-1-5 -i -b comparison

**Comment by DavidKorczynski** [comment]
The latest one using local FI works: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-16-537-dk-5312121-comparison/index.html

**Review by oliverchang — APPROVED** [review]
thanks!

**Pull request merged**
