### PR TITLE
[Experiment only] Fix constructor experiment

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Experiment for https://github.com/google/oss-fuzz-gen/pull/270

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun request_pr_exp.py -n dk-test-jvm-1 -m vertex_ai_gemini-1-5 -b jvm

**Comment by DavidKorczynski** [comment]
/gcbrun request_pr_exp.py -n dk-test-jvm-2 -m vertex_ai_gemini-1-5 -b jvm

**Comment by oliverchang** [comment]
/gcbrun request_pr_exp.py -n test-jvm -m vertex_ai_gemini-1-5 -b jvm

**Comment by oliverchang** [comment]
/gcbrun request_pr_exp.py -n test-jvm2 -m vertex_ai_gemini-1-5 -b jvm

**Comment by oliverchang** [comment]
/gcbrun request_pr_exp.py -n test-jvm2 -m vertex_ai_gemini-1-5 -b jvm

**Comment by oliverchang** [comment]
/gcbrun exp -n test-jvm2 -m vertex_ai_gemini-1-5 -b jvm

**Comment by oliverchang** [comment]
/gcbrun exp -n test-jvm3 -m vertex_ai_gemini-1-5 -b jvm

**Comment by DavidKorczynski** [comment]
Experiment is looking good

**Comment by DavidKorczynski** [comment]
Merged in https://github.com/google/oss-fuzz-gen/pull/270

**Pull request closed without merging**
