### PR TITLE
Fix various benchmarks.

### PR DESCRIPTION
**Pull request by oliverchang**
This restores some of the fixes from
https://github.com/google/oss-fuzz-gen/commit/90a87bce622a9d823ba2080c96310289fb3e6345, and adds some new fixes too.

They were lost after we regenerated the benchmarks.

### CODE REVIEW

**Comment by oliverchang** [comment]
TBR. merging this in to see if we can get a run over the weekend.

**Comment by oliverchang** [comment]
Merging this in to get a weekly run in over the weekend.

**Comment by DonggeLiu** [comment]
Ah I am updating the all experiments as FI has done so in the API.
I will manually apply these changes in mine, then.

**Comment by DonggeLiu** [comment]
BTW, could you show me hope to merge this PR without approval?
I am trying to merge https://github.com/google/oss-fuzz-gen/pull/162, thanks!

**Pull request merged**
