### PR TITLE
run_all_experiments: update project summary data on-the-fly

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Prior to this commit project summary stats were generated only when all experiments had compled, i.e. all benchmarks running should terminate. This causes issues when, for some reason, some benchmarks may not terminate properly or terminate at all. This was observed on some large-scale experiments where 10-20 benchmarks did not finish, and, consequently the full run_experiment_all didn't terminate proper. However, in this case we stil want project summary stats for the 1000+ other benchmarks that have been analyzed.

This fixes it by updated benchmarks stats after each completed benchmark run.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-ft-102 -m vertex_ai_gemini-1-5 -b minor-for-ci -i

**Comment by DavidKorczynski** [comment]
First experiment is looking good -- as well as all locals

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-ft-105 -m vertex_ai_gemini-1-5 -b from-test-small -i

**Comment by DavidKorczynski** [comment]
second experiment using test migration benchmarks is also looking good with results updating during run

**Review by arthurscchan — APPROVED** [review]

**Pull request merged**
