### PR TITLE
Upgrade Gemini Pro 1.5 to GA.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@DonggeLiu - any way to verify this on OSS-Fuzz. Locally it runs fine for experimental script.

**Comment by oliverchang** [comment]
> @DonggeLiu - any way to verify this on OSS-Fuzz. Locally it runs fine for experimental script.

You can run experiments via PR with a command like https://github.com/google/oss-fuzz-gen/pull/501#issuecomment-2244200775

**Comment by inferno-chromium** [comment]
> > @DonggeLiu - any way to verify this on OSS-Fuzz. Locally it runs fine for experimental script.
> 
> You can run experiments via PR with a command like [#501 (comment)](https://github.com/google/oss-fuzz-gen/pull/501#issuecomment-2244200775)

Thanks, that worked.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
