### PR TITLE
Display triage prompt on web (#538)

### PR DESCRIPTION
**Pull request by DonggeLiu**
From #538: This PR displays the triage prompt on the web, making it easier to read and evaluate the factors affecting LLM triage.

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
I think this was only for running an experiment and not to be merged -- the changes were merged here: https://github.com/google/oss-fuzz-gen/pull/538/files

**Comment by DavidKorczynski** [comment]
Closing this as it's already merged in -- however, I'm not sure the UI is displaying what's in intended when looking at https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-19-546-my-comparison/index.html

**Comment by DavidKorczynski** [comment]
> Closing this as it's already merged in -- however, I'm not sure the UI is displaying what's in intended when looking at https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-19-546-my-comparison/index.html

This is wrong -- looking at it deeper it looks like the triage display is working as intended!

**Comment by mihaimaruseac** [comment]
It is not on the `main` branch. #538 was merging from one feature branch to another.

But that being said, I'd leave it to you/Dongge to decide if this should go on main branch or not.

**Comment by DavidKorczynski** [comment]
> But that being said, I'd leave it to you/Dongge to decide if this should go on main branch or not.

Ah! Good catch! I'll reopen in that case

**Comment by DavidKorczynski** [comment]
Experiment is looking good

**Comment by DonggeLiu** [comment]
Yep, thanks both @DavidKorczynski @mihaimaruseac 
This is mainly because @fdt622 does not access to run experiments on PRs, so I am running a final test experiment here before merging.

Does everything look good to you @fdt622 ?
If so we can merge this now.

**Comment by fdt622** [comment]
> Yep, thanks both @DavidKorczynski @mihaimaruseac This is mainly because @fdt622 does not access to run experiments on PRs, so I am running a final test experiment here before merging.
> 
> Does everything look good to you @fdt622 ? If so we can merge this now.

Thank you all. So far, the results look good.

**Comment by mihaimaruseac** [comment]
In this case, let's merge it. Thank you, everyon!

**Pull request merged**
