### PR TITLE
JVM: Add resources closing suggestion to JVM prompts

### PR DESCRIPTION
**Pull request by arthurscchan**
This PR fixes the prompt generation of JVM projects. It includes new requirements to close resource classes to reduce the chance of OOM in generated fuzzers before too many opened resource objects.

### CODE REVIEW

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-528-1 -m vertex_ai_gemini-1-5 -b jvm-small

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-528-2 -m vertex_ai_gemini-1-5 -b jvm-medium

**Review by DavidKorczynski — CHANGES_REQUESTED** [review]
does it make sense to use an API instead? I think this is what we were aiming to do and the benchmark is slowly getting quite bloated

**Comment by arthurscchan** [comment]
In favour of adding the API in FI, this PR is no longer needed.

**Pull request closed without merging**
