### PR TITLE
Update project_targets.py

### PR DESCRIPTION
**Pull request by ch1hyun**
Fixed comments on lines 106 and 228 (corrected ‘targe’ to ‘target’)

### CODE REVIEW

**Review by DavidKorczynski — CHANGES_REQUESTED** [review]
Could you please sign the CLA @ch1hyun ?

**Comment by ch1hyun** [comment]
@DavidKorczynski sorry. I just updated my CLA.

**Review by DonggeLiu — APPROVED** [review]
Thanks!

**Pull request merged**
