### PR TITLE
oss_fuzz_checkout: avoid breaking on permission errors

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Change from TemporaryDirectory to mkdtemp. TemporaryDirectory has a destructor that can fail, and the exception can't be caught. This fixes it as there is no destructor on the string returned by `mkdtemp`.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Difference in behaviour:

Before PR:

```sh
$ ./run_all_experiments.py --model=gpt-3.5-turbo --benchmarks-directory=./benchmark-sets/comparison2/
Running 2 experiment(s) in parallel.
Downloaded human-written fuzz targets of tinyxml2 from Google Cloud Bucket: oss-fuzz-llm-public.
Generating targets for tinyxml2 XMLNode * tinyxml2::XMLElement::ShallowClone(XMLDocument *) using gpt-3.5-turbo..
Generated:
 results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/raw_targets/01.cpp
 results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/raw_targets/02.cpp
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with address
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Running tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with address
Running tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with coverage
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with coverage
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with coverage
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with coverage
Successfully built /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/01.cpp without LLM code fix.
Successfully built /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp without LLM code fix.
Warning: NO_COV_INCREASE in tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02.
Loading existing summary.json from tinyxml2/reports/20240328/linux/summary.json
Loading existing textcov from tinyxml2/textcov_reports/20240328/xmltest.covreport
Result for tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01: crashes=False, coverage=0.06469689251146205 (127/1963), coverage diff=0.020887728459530026 (56/2681)

**** Finished benchmark tinyxml2, XMLNode * tinyxml2::XMLElement::ShallowClone(XMLDocument *) ****
build success rate: 1.0, crash rate: 0.5, found bug: 0, max coverage: 0.06469689251146205, max line coverage diff: 0.020887728459530026
max coverage sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/01.cpp
max coverage diff sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/01.cpp
max coverage diff report: None


**** FINAL RESULTS: ****


================================================================================
*tinyxml2, XMLNode * tinyxml2::XMLElement::ShallowClone(XMLDocument *)*
build success rate: 1.0, crash rate: 0.5, found bug: 0, max coverage: 0.06469689251146205, max line coverage diff: 0.020887728459530026
max coverage sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/01.cpp
max coverage diff sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/01.cpp
max coverage diff report: None

WARNING:root:No permission to remove /tmp/tmp3ds95zp9
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 662, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 667, in _exitfunc
    f()
  File "/usr/lib/python3.10/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.10/tempfile.py", line 998, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "/usr/lib/python3.10/tempfile.py", line 994, in _rmtree
    _rmtree(name, onerror=onerror)
  File "/usr/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.10/shutil.py", line 664, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.10/tempfile.py", line 978, in onerror
    resetperms(_os.path.dirname(path))
  File "/usr/lib/python3.10/tempfile.py", line 974, in resetperms
    _os.chmod(path, 0o700)
PermissionError: [Errno 1] Operation not permitted: '/tmp/tmp3ds95zp9/build/work'
```


After PR:

```sh
(.venv) dav@ubuntu-main:~/code/2024/tosg2/oss-fuzz-gen$ ./run_all_experiments.py --model=gpt-3.5-turbo --benchmarks-directory=./benchmark-sets/comparison2/
Running 2 experiment(s) in parallel.
Downloaded human-written fuzz targets of tinyxml2 from Google Cloud Bucket: oss-fuzz-llm-public.
Generating targets for tinyxml2 XMLNode * tinyxml2::XMLElement::ShallowClone(XMLDocument *) using gpt-3.5-turbo..
Generated:
 results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/raw_targets/01.cpp
 results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/raw_targets/02.cpp
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with address
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with address
Running tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01
Failed to run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Fixing /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp with gpt-3.5-turbo, attempt 1.
Will use the longest fix: results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02-F1/01.rawoutput.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Failed to run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Fixing /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp with gpt-3.5-turbo, attempt 2.
Will use the longest fix: results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02-F2/01.rawoutput.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Failed to run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Fixing /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp with gpt-3.5-turbo, attempt 3.
Will use the longest fix: results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02-F3/01.rawoutput.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Failed to run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Fixing /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp with gpt-3.5-turbo, attempt 4.
Will use the longest fix: results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02-F4/01.rawoutput.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with coverage
Failed to run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Fixing /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp with gpt-3.5-turbo, attempt 5.
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01 with coverage
Successfully built /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/01.cpp without LLM code fix.
Warning: NO_COV_INCREASE in tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-01.
Will use the longest fix: results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02-F5/01.rawoutput.
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with address
Running tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02
********** Failed to run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02. **********
Building tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with coverage
Successfully run tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02 with coverage
Successfully fixed /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp with gpt-3.5-turbo in 5 iterations.
Warning: FP_CRASH_NEAR_INIT in tinyxml2-znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente-02.

**** Finished benchmark tinyxml2, XMLNode * tinyxml2::XMLElement::ShallowClone(XMLDocument *) ****
build success rate: 1.0, crash rate: 1.0, found bug: 0, max coverage: 0.0, max line coverage diff: 0.0
max coverage sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp
max coverage diff sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp
max coverage diff report: None


**** FINAL RESULTS: ****


================================================================================
*tinyxml2, XMLNode * tinyxml2::XMLElement::ShallowClone(XMLDocument *)*
build success rate: 1.0, crash rate: 1.0, found bug: 0, max coverage: 0.0, max line coverage diff: 0.0
max coverage sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp
max coverage diff sample: /home/dav/code/2024/tosg2/oss-fuzz-gen/results/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente/fixed_targets/02.cpp
max coverage diff report: None

WARNING:root:No permission to remove /tmp/tmpfdmwg9o3
```

**Comment by DonggeLiu** [comment]
Thanks for this PR, @DavidKorczynski!
Yes, it is definitely some noise we'd like to eliminate.

Just to double-check, I noticed that this was submitted from a fork of this repo before [testing your new access](https://github.com/google/oss-fuzz-gen/pull/194), which explains why the first CI failed.

Would it be possible for you to resubmit this PR as a branch of this repo, so that I can run experiments for you?
Thanks, and hope this is not too much trouble : )

**Comment by DavidKorczynski** [comment]
Yup, for sure: https://github.com/google/oss-fuzz-gen/pull/202

**Comment by DonggeLiu** [comment]
Thanks!

**Pull request closed without merging**
