### PR TITLE
Set back temperature to 0.4

### PR DESCRIPTION
**Pull request by DonggeLiu**
This PR:
1. Sets back the default temperature to 0.4.
2. Continues #448 to allow different temperatures for fuzz target samples.

 I will re-run a full exp to validate their effect.

The recent [08-03 report](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-03-weekly-all/) contains regressions due to model inadequacies, such as:
```c++
fuzz/parse.cc:13:21: error: calling 'parse_url<url>' with incomplete return type 'url'
   13 |   ada::url result = ada::parser::parse_url(url, base_url);
```

This is likely because we [increased the temperature](https://github.com/google/oss-fuzz-gen/pull/448/files#diff-0d648b28bb6b85213eb0ff1c3954edd4b710ff8b219eb7dc89b294108dfedb3eL52-R52). Maybe code generation needs to be more strict and less random?

Also #448  did not pass `VARY_TEMPERATURE` to `run_all_experiments.py`, this PR fixes that and support it in PR experiments.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg-1 -ns 10 -f

**Comment by DonggeLiu** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-05-527-dg-1-comparison/index.html

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg-2 -ns 10 -f

**Review by mihaimaruseac — APPROVED** [review]

**Review by oliverchang — APPROVED** [review]

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg-3 -ns 10

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg-4 -ns 10

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg-4 -ns 10 -nf 5 -f

**Comment by DonggeLiu** [comment]
The report looks better than today's daily report:
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-07-527-dg-4-comparison/index.html
vs
https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-07-daily-comparison/index.html

**Comment by DonggeLiu** [comment]
Started a full exp for this.
REPORT:  https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-08-07-weekly-all/
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1/llm-experiment-large/default/manual-08-07/details?mods=logs_tg_prod&project=oss-fuzz

**Pull request merged**
