### PR TITLE
Full experiment with the new C-specific prompt

### PR DESCRIPTION
**Pull request by DonggeLiu**
Running a full experiment with the new C-specific prompt.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
@DavidKorczynski: Are there any other changes required to use the C-specific prompt?
Would you recommend updating the benchmarks before the exp?

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski: Are there any other changes required to use the C-specific prompt?

No

> Would you recommend updating the benchmarks before the exp?

We can use these benchmarks for pure C projects only: https://github.com/google/oss-fuzz-gen/pull/371

**Comment by DonggeLiu** [comment]
The experiment report with c-benchmarks only:
https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-06-23-weekly-all/

The incorrect header error persists.
Take [`bind9`](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-06-23-weekly-all/sample/output-bind9-dns_view_freezezones/01) as an example:
The prompt provided the header full path (`/src/bind9/lib/dns/include/dns/view.h`), but LLM still used the incorrect path (`/src/bind9/lib/isc/include/dns/view.h`), which highlights the need to fix this programmatically.

@DavidKorczynski will you address this?

**Comment by DonggeLiu** [comment]
Re-running under the same config as [2024-06-23-weekly-all/](https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-06-23-weekly-all/) with C benchmarks only:
https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-06-24-weekly-all/

**Comment by DonggeLiu** [comment]
Outdated.

**Pull request closed without merging**
