### PR TITLE
Fix undefined reference

### PR DESCRIPTION
**Pull request by DonggeLiu**
1. Add the header file of the function-under-test in the code generation prompt.
2. Add the header file or source code file of the missing function in the code fixing prompt (C projects mostly).
3. Related instructions.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
/gcbrun exp -f  -ns 10 -nf 5 -n dg

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -ns 10 -nf 5 -n dg

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -ns 10 -nf 5 -n dg

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -ns 10 -nf 5 -n dg

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -ns 10 -nf 5 -n dg

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -ns 10 -nf 5 -n dg

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -ns 10 -nf 5 -n dg-1

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -ns 10 -nf 5 -n dg-1

**Comment by DonggeLiu** [comment]
Strange that this works locally but not on the server:
```
**** Finished benchmark ada-url, bool ada_can_parse_with_base(const char *, size_t, const char *, size_t) ****
build success rate: 1.0, crash rate: 0.0, found bug: 0, max coverage: 0.18582758876287897, max line coverage diff: 0.002601156069364162
max coverage sample: /usr/local/google/home/donggeliu/Code/oss-fuzz-gen/results-2024-07-12-21-41/output-ada-url-ada_can_parse_with_base/fixed_targets/01.cc
max coverage diff sample: /usr/local/google/home/donggeliu/Code/oss-fuzz-gen/results-2024-07-12-21-41/output-ada-url-ada_can_parse_with_base/fixed_targets/01.cc
max coverage diff report: gs://oss-fuzz-gcb-experiment-run-logs/dg-curl56df3ed9-b0f1-4e4e-a02e-b1008c8f63fc.coverage
```

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -i -ns 10 -nf 5 -n dg-2

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -i -ns 10 -nf 5 -n dg-3

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -i -ns 10 -nf 5 -n dg-3

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -i -ns 10 -nf 5 -n dg-4

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -i -ns 10 -nf 5 -n dg-5

**Review by mihaimaruseac — APPROVED** [review]

**Comment by DonggeLiu** [comment]
/gcbrun exp -f -i -ns 10 -nf 5 -n dg

**Review by mihaimaruseac — APPROVED** [review]

**Comment by DonggeLiu** [comment]
Increase build rate of:
1. `ada_can_parse_with_base` from [0 to 100%](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-07-14-465-dg-comparison/benchmark/output-ada-url-ada_can_parse_with_base/index.html),
2. `crxLoadDecodeLoop` from [60% to 100%](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-07-14-465-dg-comparison/benchmark/output-libraw-_zn6libraw17crxloaddecodeloopepvi/index.html),
3. `sf_open` from [20% to 100%](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-07-14-465-dg-comparison/benchmark/output-libsndfile-sf_open/index.html),
4. plus other random fluctuations between:
    1. https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-07-16-daily-comparison/index.html 
    5. https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-07-14-465-dg-comparison/index.html

**Comment by DonggeLiu** [comment]
Some other improvements:
1. Get function header/source file when FI implements the API (function name -> function signatures for C++ projects)
2. Group the instructions based on the change needed (e.g., to fix X, do a),b),and c).
3. Add line breaks to make instructions in the prompt more human-readable.
4. Consider re-organizing the rule-applying logic implementation.

**Pull request merged**
