### PR TITLE
Update Openai support to >= v1.0.0

### PR DESCRIPTION
**Pull request by MarkLee131**
Hi, I upgraded the oss-fuzz-gen project’s OpenAI SDK dependency from version 0.27.8 to version >=1.0.0, in line with OpenAI's official recommendations. This move is motivated by the significant enhancements introduced in version 1.0.0, which OpenAI details [here](https://github.com/openai/openai-python/discussions/742).

Key improvements include:
- A complete rewrite of the library for robustness and error resilience.
- Introduction of explicit client instantiation, replacing the global default and offering more flexible SDK interaction.

After upgrading to v1.16.2 (the latest available), I tested the integration with my API key and confirmed full functionality. This upgrade aligns oss-fuzz-gen with current best practices and ensures compatibility with future developments in AI technologies. 

Hope it helps.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
On a quick skim this looks good, but let me run some experiments today and then I will approve.

Meanwhile can you fix the lint CI, please?

**Comment by MarkLee131** [comment]
Hi, I have finished the fix.

**Review by mihaimaruseac — APPROVED** [review]
Thank you! This LGTMs

**Comment by DonggeLiu** [comment]
Thanks @MarkLee131 and @mihaimaruseac !

**Pull request merged**
