### PR TITLE
JVM: Fix benchmark for jvm-all

### PR DESCRIPTION
**Pull request by arthurscchan**
This PR relates to #507 and continue to modify, adds, removes and fixes the benchmark yaml files in the jvm-all benchmark set for JVM projects. The end goal is to have better coverage gain result shown by the benchmark.

### CODE REVIEW

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-516-1 -m vertex_ai_gemini-1-5 -b jvm-all

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-516-2 -m vertex_ai_gemini-1-5 -b jvm-all

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-516-3 -m vertex_ai_gemini-1-5 -b jvm-all

**Comment by DavidKorczynski** [comment]
Experiment looks good: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-01-516-ascc-jvm-pr-516-3-jvm-all/index.html

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
