### PR TITLE
introduce cloud logging

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dgkbbb21 -m vertex_ai_gemini-1-5 -i -b minor-for-ci

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dgkbbb22 -m vertex_ai_gemini-1-5 -i -b minor-for-ci

**Comment by DavidKorczynski** [comment]
the logs are looking good now

**Comment by DonggeLiu** [comment]
Thanks for fixing this!

**Review by DonggeLiu — APPROVED** [review]

**Pull request merged**
