### PR TITLE
report: fix java coverage links

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Links are not working for Java coverage reports because of mismatch with report/index.html

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n david-report-test -m vertex_ai_gemini-1-5 -i -b jvm-small

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n david-report-test2 -m vertex_ai_gemini-1-5 -i -b jvm-small

**Comment by DavidKorczynski** [comment]
Java experiment is good, coverage reports have links

**Comment by DavidKorczynski** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-04-571-david-report-test2-jvm-small/index.html

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n david-report-test3 -m vertex_ai_gemini-1-5 -i -b minor-for-ci

**Comment by DavidKorczynski** [comment]
non java works well too: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-09-04-571-david-report-test3-minor-for-ci/index.html

**Review by arthurscchan — APPROVED** [review]
Just a remark, if the project use non-conventional package name with no dot character, this logic will still fail.

**Comment by DavidKorczynski** [comment]
yeah, it's not a perfect solution, but will do as an improvement now. Making it clean requires larger refactoring so I'm holding on for a minute with that.

**Pull request merged**
