### PR TITLE
benchmarks: add a larger set of test-to-harness targets

### PR DESCRIPTION
**Pull request by DavidKorczynski**
For many projects there are more test files available, but am limiting it to 9 files for now. This should be good for assessing quality for now. There is ~160 projects in this benchmark.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-test-to-harness-exp-2 -m vertex_ai_gemini-1-5 -i -b comparison from-test-small

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-test-to-harness-exp-3 -m vertex_ai_gemini-1-5 -i -b from-test-small

**Comment by DavidKorczynski** [comment]
The small is looking good https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-18-544-dk-test-to-harness-exp-3-from-test-small/index.html

Testing on the larger now

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-test-to-harness-exp-4 -m vertex_ai_gemini-1-5 -i -b from-test-large

**Review by mihaimaruseac — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Large scale experiment: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-18-544-dk-test-to-harness-exp-4-from-test-large/index.html

**Pull request merged**
