### PR TITLE
Fix multiple threads share one logger

### PR DESCRIPTION
**Pull request by maoyixie**
The original code ([_fuzzing_pipelines](https://github.com/google/oss-fuzz-gen/blob/c9f87defe821ab66f123b7730b59eb2a93c6608b/run_one_experiment.py#L336), [_fuzzing_pipeline](https://github.com/google/oss-fuzz-gen/blob/c9f87defe821ab66f123b7730b59eb2a93c6608b/run_one_experiment.py#L321), [get_trial_logger](https://github.com/google/oss-fuzz-gen/blob/c9f87defe821ab66f123b7730b59eb2a93c6608b/logger.py#L126)) will cause multiple threads in the thread pool to share a logger. Now use threading.local() to create a separate logger for each thread.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Wow, thanks @maoyixie!
Not sure how I missed this, please always feel free to ping me : )

**Comment by DonggeLiu** [comment]
Unfortunately this seems to have the same problem:
```
# Running 3 trials.
2024-11-22 13:33:00 [Trial ID: 01] DEBUG [pipeline.execute]: Pipeline starts
2024-11-22 13:33:00 [Trial ID: 01] DEBUG [pipeline.execute]: Pipeline starts
2024-11-22 13:33:00 [Trial ID: 01] DEBUG [pipeline.execute]: Pipeline starts
```

Does it work on your local machine?

**Comment by maoyixie** [comment]
Sorry for the mistake. I have refixed and tested it on the local machine.

**Comment by DonggeLiu** [comment]
Thanks for fixing this!
Local exp works perfect now, let me run a final cloud exp to double-check everything if fine too.

**Comment by DonggeLiu** [comment]
Report looking good:
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-11-24-720-my-comparison/index.html

**Review by DonggeLiu — APPROVED** [review]

**Pull request merged**
