### PR TITLE
Add `extern` only when a c project has c++ fuzz targets

### PR DESCRIPTION
**Pull request by DonggeLiu**
Almost all regressions in https://github.com/google/oss-fuzz-gen/pull/382#issuecomment-2190303945 are due to C projects using C++ fuzz targets.
This PR resolves that.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Seeing more buildable benchmarks with the fix:
image

**Review by jonathanmetzman — COMMENTED** [review]
LGTM

**Pull request merged**
