### PR TITLE
[DO NOT MERGE] LLM-based crash triaging

### PR DESCRIPTION
**Pull request by DonggeLiu**
Experiment based on the idea from #221 and more.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
@fdt622 the experiment is running at here.
Do you have access to the report, btw?

**Comment by fdt622** [comment]
> @fdt622 the experiment is running at here. Do you have access to the report, btw?

No, I do not have the access.

**Comment by DonggeLiu** [comment]
Not sure why the previous exp did not launch successfully, retrying ...

**Comment by DonggeLiu** [comment]
/gcbrun exp -n dg-bug -f -b bug

**Comment by DonggeLiu** [comment]
Incorrect triage:
1. [`rediscommand`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-06-13-252-dg-comparison/sample/output-hiredis-rediscommand/06) has incorrect triage:
    * The fuzz target did check 'the return value of `redisFormatCommand`', the triage says otherwise. We can try providing the erroneous line in the fixer prompt.

No triage:
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-06-13-252-dg-comparison/sample/output-libarchive-archive_entry_linkify/05

Correct triage:
1. [`archive_entry_linkify`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-06-13-252-dg-comparison/sample/output-libarchive-archive_entry_linkify/01). LLM can probably even fix the error given the triage.

**Comment by DonggeLiu** [comment]
JOB: https://console.cloud.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-252-dg-bug
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-06-13-252-dg-bug-bug/index.html

**Comment by fdt622** [comment]
> Incorrect triage:
> 
> 1. [`rediscommand`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-06-13-252-dg-comparison/sample/output-hiredis-rediscommand/06) has incorrect triage:
>    
>    * The fuzz target did check 'the return value of `redisFormatCommand`', the triage says otherwise. We can try providing the erroneous line in the fixer prompt.
> 
> No triage: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-06-13-252-dg-comparison/sample/output-libarchive-archive_entry_linkify/05
> 
> Correct triage:
> 
> 1. [`archive_entry_linkify`](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-06-13-252-dg-comparison/sample/output-libarchive-archive_entry_linkify/01). LLM can probably even fix the error given the triage.

Hi, I have fixed the no triage problem in #374. Besides, I slice code and point out concrete code line in the prompt.

**Comment by DonggeLiu** [comment]
Thanks @fdt622 !
Could you please 1) resolve the merge conflict on this PR (#252), 2) rebase this PR on the main branch, and 3) rebase #374 on this PR?

Sorry that you have to go through this trouble but I noticed that #374 contains code changes from other PRs (e.g., `modifying ci/k8s/pr-exp.yaml`), which is caused by:
1. This PR (#252) is not up-to-date with main
2. The new PR (#374) is based on newer commits in main
Hence, Github misinterprets those new commits from main as part of #374, which makes it difficult to reviewing and will lead to confusing conflicts when merged into this PR.



If rebasing #374 is too complicated, this is probably simpler:
1) resolve the merge conflict on this PR (#252),
2) rebase this PR on the main branch,
3) Get the new commits in #374 with `git reflog`
4) Create a new branch and `git cherry-pick` those new commits.

**Comment by DonggeLiu** [comment]
I also created a clean branch/PR with the latest main in #375.
Feel free to use it (or test merging into it) if you like.

**Comment by fdt622** [comment]
> Thanks @fdt622 ! Could you please 1) resolve the merge conflict on this PR (#252), 2) rebase this PR on the main branch, and 3) rebase #374 on this PR?
> 
> Sorry that you have to go through this trouble but I noticed that #374 contains code changes from other PRs (e.g., `modifying ci/k8s/pr-exp.yaml`), which is caused by:
> 
> 1. This PR ([[DO NOT MERGE] LLM-based crash triaging #252](https://github.com/google/oss-fuzz-gen/pull/252)) is not up-to-date with main
> 2. The new PR ([Enhance LLM-based crash triaging with project function code #374](https://github.com/google/oss-fuzz-gen/pull/374)) is based on newer commits in main
>    Hence, Github misinterprets those new commits from main as part of [Enhance LLM-based crash triaging with project function code #374](https://github.com/google/oss-fuzz-gen/pull/374), which makes it difficult to reviewing and will lead to confusing conflicts when merged into this PR.
> 
> If rebasing #374 is too complicated, this is probably simpler:
> 
> 1. resolve the merge conflict on this PR ([[DO NOT MERGE] LLM-based crash triaging #252](https://github.com/google/oss-fuzz-gen/pull/252)),
> 2. rebase this PR on the main branch,
> 3. Get the new commits in [Enhance LLM-based crash triaging with project function code #374](https://github.com/google/oss-fuzz-gen/pull/374) with `git reflog`
> 4. Create a new branch and `git cherry-pick` those new commits.

Thank you for your explanation @DonggeLiu, I have resolve the conflict on #252 and rebase #252 on main branch, see #376

**Comment by DonggeLiu** [comment]
> Thank you for your explanation @DonggeLiu, I have resolve the conflict on #252 and rebase #252 on main branch, see #376

Thanks for looking into this so quickly!
But it seems that #376 still has merge conflicts : )

BTW, seeing other people's commit in your PR is normally a bad sign for 'something went wrong':
image

**Comment by fdt622** [comment]
> > Thank you for your explanation @DonggeLiu, I have resolve the conflict on #252 and rebase #252 on main branch, see #376
> 
> Thanks for looking into this so quickly! But it seems that #376 still has merge conflicts : )
> 
> BTW, seeing other people's commit in your PR is normally a bad sign for 'something went wrong': image

Hi @DonggeLiu , I have closed #376 and #374, sorry for submitting other's commit in my PR. Based on #375, I have resolved the conflict on #252 and rebase #252 on main branch, see #379. After #379 is merged, I would rebase #374 on #379. Thanks!

**Comment by fdt622** [comment]
> > > Thank you for your explanation @DonggeLiu, I have resolve the conflict on #252 and rebase #252 on main branch, see #376
> > 
> > 
> > Thanks for looking into this so quickly! But it seems that #376 still has merge conflicts : )
> > BTW, seeing other people's commit in your PR is normally a bad sign for 'something went wrong': image
> 
> Hi @DonggeLiu , I have closed #376 and #374, sorry for submitting other's commit in my PR. Based on #375, I have resolved the conflict on #252 and rebase #252 on main branch, see #379. After #379 is merged, I would rebase #374 on #379. Thanks!

clear other's commit in my pr, all rebase done, see #379.

**Comment by DonggeLiu** [comment]
Superseded by #375.

**Pull request closed without merging**
