### PR TITLE
report: Add macro insights to HTML report

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This makes it a lot easier to track progress and also spot regressions.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Screenshot 2024-07-06 174114

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-test-web-335 -m vertex_ai_gemini-1-5 -b comparison

**Comment by DavidKorczynski** [comment]
Experiment is looking good

**Review by DonggeLiu — APPROVED** [review]
Thanks!

**Pull request merged**
