### PR TITLE
[DO NOT MERGE] Test using project context from Fuzz Introspector (#144)

### PR DESCRIPTION
**Pull request by DonggeLiu**
This PR is based on #144 and is only designed to run experiments for it.

It is separated from #144 so that we can merge it and only enable context on all experiments when we are more stably relying on FI context info.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-150-dg
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-12-150-dg-comparison/index.html
BUCKET: https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-12-150-dg-comparison
BUCKET GS: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-12-150-dg-comparison`

**Comment by DonggeLiu** [comment]
The report is problematic for several reasons:
1. Failed to generate prompt (e.g., the benchmark appears to be still *running* because of this, like [libvpx-const uint8_t * decode_tiles_row_wise_mt(VP9Decoder *, const uint8_t *, const uint8_t *)](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-12-150-dg-comparison/benchmark/output-libvpx-decode_tiles_row_wise_mt)).
2. Regression. Low build rate of [tinyxml2-XMLNode * const XMLElement::ShallowClone(XMLDocument *)](https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-12-150-dg-comparison/benchmark/output-tinyxml2-_znk8tinyxml210xmlelement12shallowcloneepns_11xmldocumente).
3. Low coverage diff. All benchmarks got 0 coverage diff.

@trashvisor would you mind investigating this further when you have time?
Thanks!

**Comment by trashvisor** [comment]
JOB: https://pantheon.corp.google.com/kubernetes/job/us-central1-c/llm-experiment/default/ofg-pr-150-ggryan
REPORT: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-03-14-150-ggryan-comparison/index.html
BUCKET: https://pantheon.corp.google.com/storage/browser/oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-14-150-ggryan-comparison
BUCKET GS: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-03-14-150-ggryan-comparison`

**Comment by trashvisor** [comment]
Just going to run a quick comp benchmark before a full one

**Comment by DonggeLiu** [comment]
Continued at #192 to avoid repeatedly resolving merge conflicts.

**Pull request closed without merging**
