### PR TITLE
Fix fuzz target binary name and source file path

### PR DESCRIPTION
**Pull request by DonggeLiu**
Some projects had [>0 build rate but 0 coverage](https://docs.google.com/spreadsheets/d/1bx1YeKc7cqJr9Qlt_Qrw06EV84p5OTbFQqbfVBPLKO4/edit?resourcekey=0-qvVvym2ZIUNIFn3jp-osLw&gid=1522358986#gid=1522358986) on all benchmarks, because of their incorrect fuzz target binary name (and/or fuzz target path).

This PR fixes that.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
[capstone](https://github.com/google/oss-fuzz-gen/pull/524/files#diff-961d1413b140f12321268492c41d10e4c8e2f6036b0be9ea69e3f8dd66ffe277) and [pigweed](https://github.com/google/oss-fuzz-gen/pull/524/files#diff-7e2c31b9f164af0768eefbc5eb87e6dd88861e13ee186c8e73d996f3c4dbb359) are two special cases who cannot build with OSS-Fuzz.

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg -b missing-bin

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
CC @DavidKorczynski Is there some more reliable way we can get these mappings?

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg -b missing-bin -ns 10 -nf 5 -to 1800

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg -b missing-bin -ns 10 -nf 5 -to 1800 -f

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg-1 -b missing-bin -ns 10 -nf 5 -to 1800 -f

**Comment by DonggeLiu** [comment]
/gcbrun exp -i -n dg-1 -b missing-bin -ns 10 -nf 5 -to 1800 -f

**Comment by DonggeLiu** [comment]
https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-08-03-524-dg-1-missing-bin/index.html

**Pull request merged**
