### PR TITLE
extend coverage stats analysis in reporting

### PR DESCRIPTION
**Pull request by DavidKorczynski**
- adds comparison to the current state of OSS-Fuzz. This makes it easy to see how much improvement the experiment has across the OSS-Fuzz landscape.
- adds a new metric, "relative coverage gain" which compares the newly achieved coverage per project relatiev to the existing coverage lines. The point is here the metric of coverage gain relative to total line number does not tell all about the achievements. An interesting metric is how much have been improved relative to the existing manually achieved fuzzing.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n dk-improve-cov-and-test-non-fi-projects -m vertex_ai_gemini-1-5 -i -b test-mix-new-projects

**Comment by DavidKorczynski** [comment]
Experiment looks good: https://llm-exp.oss-fuzz.com/Result-reports/ofg-pr/2024-10-30-678-dk-improve-cov-and-test-non-fi-projects-test-mix-new-projects/index.html

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
