### PR TITLE
JVM: test to harness approach for Java project

### PR DESCRIPTION
**Pull request by arthurscchan**
This PR adds JVM project support for the test-to-harness approach initiated in #511. This PR also adds new benchmark set using the test-to-harness approach on Java projects.

### CODE REVIEW

**Comment by arthurscchan** [comment]
/gcbrun exp -n ascc-jvm-pr-592-1 -m vertex_ai_gemini-1-5 -i -b test-to-harness-jvm

**Comment by DavidKorczynski** [comment]
fyi, I think there's a bug in the java coverage calculation which means we're not showing the correct gains. Could you manually cross-check the gains?

**Comment by DavidKorczynski** [comment]
> fyi, I think there's a bug in the java coverage calculation which means we're not showing the correct gains. Could you manually cross-check the gains?

Looking at the results, the coverage looks good, so let's discard the above thought for now.

**Review by DavidKorczynski — CHANGES_REQUESTED** [review]
could you rename the benchmark dir to `*-small`, and then a follow-up PR with a folder with a full benchmark suite

**Comment by DavidKorczynski** [comment]
Java experiment looks good.

Will start a vanilla experiment just to verify there's no regressions

**Comment by DavidKorczynski** [comment]
/gcbrun exp -n ascc-jvm-pr-592-1-david -m vertex_ai_gemini-1-5 -i -b minor-for-ci

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
